/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package front;
import back.Planificador;
import back.Consumidores;
import back.Productores;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.Stack;
import javax.swing.JLabel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.applet.AudioClip;
import java.awt.Cursor;
import java.awt.List;
import javax.swing.JOptionPane;


/**
 *
 * @author PC
 */
public class Interfaz extends javax.swing.JFrame {
    
    Planificador bufferPrincipal = new Planificador (0);
    Consumidores consumidor = new Consumidores (bufferPrincipal);
    Productores productor = new Productores (bufferPrincipal);
    Icon puerro = new ImageIcon(getClass().getResource("/imagenes/puerro2.png"));
    
    Consumidores listaConsumidores[];
    Productores listaProductores[];
    int consumidoresActuales;
    int productoresActuales;
    
    int cantidadActual;
    Icon icono;
    AudioClip cancion;
    JLabel[] productos;
    
    JLabel prueba = new JLabel(puerro);
    
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        
        initComponents();
        
        
        prueba.setBounds(500, 500, 180, 180);
        productos = new JLabel[10];
        listaConsumidores = new Consumidores[5];
        listaProductores = new Productores[5];
        consumidoresActuales = 0;
        productoresActuales = 0;
        
        for(int i = 0;i<10;i++){
            JLabel temp = new JLabel(puerro);
            temp.setBounds(100+(i*105), 500, 100, 100);
            panelPrincipal.add(temp);
            temp.setVisible(false);
            productos[i] = temp;
        }
        Consumidores temp = new Consumidores(bufferPrincipal);
        Productores temp2 = new Productores(bufferPrincipal);
        listaConsumidores[0] = temp;
        listaProductores[0] = temp2;
        
        
        
        //panelPrincipal.add(prueba);
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        imgProductor = new javax.swing.JLabel();
        imgConsumidor = new javax.swing.JLabel();
        lblProductor = new javax.swing.JLabel();
        lblConsumidor = new javax.swing.JLabel();
        lblAlmacen = new javax.swing.JLabel();
        btnEmpezar = new javax.swing.JButton();
        lblPrograma = new javax.swing.JLabel();
        lblStatusPrograma = new javax.swing.JLabel();
        lblCantidadActual = new javax.swing.JLabel();
        btnAgregarConsumidor = new javax.swing.JButton();
        btnAgregarProductor = new javax.swing.JButton();
        lblCantidadProductores = new javax.swing.JLabel();
        lblCantidadConsumidores = new javax.swing.JLabel();
        btnSumarAlmacen = new javax.swing.JButton();
        btnRestarAlmacen = new javax.swing.JButton();
        btnEliminarProductor = new javax.swing.JButton();
        btnEliminarConsumidor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imgProductor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/productor dormir.gif"))); // NOI18N

        imgConsumidor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consumidor dormir.gif"))); // NOI18N

        lblProductor.setText("PRODUCTOR");

        lblConsumidor.setText("CONSUMIDOR");

        lblAlmacen.setText("ALMACEN");

        btnEmpezar.setBackground(new java.awt.Color(0, 255, 204));
        btnEmpezar.setText("Empezar");
        btnEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpezarActionPerformed(evt);
            }
        });

        lblPrograma.setText("PROGRAMA");
        lblPrograma.setToolTipText("");

        lblStatusPrograma.setText("DETENIDO");

        lblCantidadActual.setText("Cantidad actual: 0");

        btnAgregarConsumidor.setText("Agregar consumidor");
        btnAgregarConsumidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarConsumidorActionPerformed(evt);
            }
        });

        btnAgregarProductor.setText("Agregar productor");
        btnAgregarProductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductorActionPerformed(evt);
            }
        });

        lblCantidadProductores.setText("Productores: ");

        lblCantidadConsumidores.setText("Consumidores: ");

        btnSumarAlmacen.setBackground(new java.awt.Color(0, 153, 51));
        btnSumarAlmacen.setText("+");
        btnSumarAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumarAlmacenActionPerformed(evt);
            }
        });

        btnRestarAlmacen.setBackground(new java.awt.Color(255, 51, 0));
        btnRestarAlmacen.setText("-");
        btnRestarAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestarAlmacenActionPerformed(evt);
            }
        });

        btnEliminarProductor.setText("Eliminar productor");
        btnEliminarProductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductorActionPerformed(evt);
            }
        });

        btnEliminarConsumidor.setText("Eliminar consumidor");
        btnEliminarConsumidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarConsumidorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblCantidadProductores, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addComponent(lblProductor))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(479, 479, 479)
                        .addComponent(btnEmpezar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblCantidadActual)
                        .addGap(385, 385, 385)
                        .addComponent(lblAlmacen)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(btnSumarAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnRestarAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(lblCantidadConsumidores, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(lblConsumidor)))
                .addGap(248, 248, 248))
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(imgProductor, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(lblPrograma)
                                .addGap(78, 78, 78))
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(lblStatusPrograma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(65, 65, 65))))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(btnAgregarProductor, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnEliminarProductor, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgConsumidor, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addComponent(btnAgregarConsumidor, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(btnEliminarConsumidor, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(79, 79, 79))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblProductor))
                            .addComponent(lblConsumidor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPrograma)
                        .addGap(75, 75, 75)
                        .addComponent(lblStatusPrograma))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(lblCantidadProductores))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblCantidadConsumidores)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgProductor, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imgConsumidor, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEliminarConsumidor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnEliminarProductor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAgregarConsumidor, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAgregarProductor, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(9, 9, 9)
                        .addComponent(btnEmpezar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAlmacen)
                            .addComponent(lblCantidadActual))
                        .addGap(303, 303, 303))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSumarAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRestarAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpezarActionPerformed
        // TODO add your handling code here:
        if(!listaProductores[0].isAlive()){
            listaProductores[productoresActuales].start();
            listaConsumidores[consumidoresActuales].start();
            actualizarVentana();
            lblStatusPrograma.setText("CORRIENDO");
            btnEmpezar.setText("Detener");
            cancion = java.applet.Applet.newAudioClip(getClass().getResource("/sonidos/graze the roof.wav"));
            cancion.loop();
            
        }else if (listaProductores[0].isCorriendo()){
            for(int i = 0;i<=productoresActuales;i++){
                listaProductores[i].suspend();
                listaProductores[i].dormir();
                listaProductores[i].detener();
            }
            for (int i = 0;i<=consumidoresActuales;i++){
                listaConsumidores[i].suspend();
                listaConsumidores[i].dormir();
            }
            /*
            productor.suspend();
            consumidor.suspend();
            productor.dormir();
            consumidor.dormir();
            productor.detener();*/
            lblStatusPrograma.setText("DETENIDO");
            btnEmpezar.setText("Empezar");
            cancion.stop();
        }else{
            for(int i = 0;i<=productoresActuales;i++){
                listaProductores[i].resume();
                listaProductores[i].despertar();
                listaProductores[i].correr();
                
            }
            for (int i = 0;i<=consumidoresActuales;i++){
                listaConsumidores[i].resume();
                listaConsumidores[i].despertar();
                        
            }
            /*
            productor.resume();
            consumidor.resume();
            productor.correr();
            productor.despertar();
            consumidor.despertar();
            */
            lblStatusPrograma.setText("CORRIENDO");
            btnEmpezar.setText("Detener");
            cancion.loop();
        }
        
    }//GEN-LAST:event_btnEmpezarActionPerformed

    private void btnAgregarProductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductorActionPerformed
        // TODO add your handling code here:
        if(listaProductores[0].isAlive()){
            if(productoresActuales<4){
            productoresActuales++;
            Productores temp = new Productores(bufferPrincipal);
            listaProductores[productoresActuales] = temp;
            listaProductores[productoresActuales].start();
            }else{
                JOptionPane.showMessageDialog(null,"Nomas se pueden poner un maximo de 5 productores UnU");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Primero presiona empezar porfavor UwU");
        }
        
        
    }//GEN-LAST:event_btnAgregarProductorActionPerformed

    private void btnAgregarConsumidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarConsumidorActionPerformed
        // TODO add your handling code here:
        if(listaProductores[0].isAlive()){
            if(consumidoresActuales<4){
            consumidoresActuales++;
            Consumidores temp = new Consumidores(bufferPrincipal);
            listaConsumidores[consumidoresActuales] = temp;
            listaConsumidores[consumidoresActuales].start();
            }else{
                JOptionPane.showMessageDialog(null,"Nomas se pueden poner un maximo de 5 consumidores UnU");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Primero presiona empezar porfavor UwU");
        }
        
        
    }//GEN-LAST:event_btnAgregarConsumidorActionPerformed

    private void btnSumarAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumarAlmacenActionPerformed
        // TODO add your handling code here:
        if(cantidadActual<10){
            bufferPrincipal.sumarAlmacen();
        }else{
            JOptionPane.showMessageDialog(null, "No se pueden sumar mas, ya esta lleno UnU");
        }
        
    }//GEN-LAST:event_btnSumarAlmacenActionPerformed

    private void btnRestarAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestarAlmacenActionPerformed
        // TODO add your handling code here:
        if(cantidadActual>0){
            bufferPrincipal.restarAlmacen();
        }else{
            JOptionPane.showMessageDialog(null, "No se pueden restar mas, el almacen ya esta vacio UnU");
        }
        
    }//GEN-LAST:event_btnRestarAlmacenActionPerformed

    private void btnEliminarProductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductorActionPerformed
        // TODO add your handling code here:
        if(listaProductores[0].isAlive()){
            if(productoresActuales>0){
                listaProductores[productoresActuales].terminarHilo();
                productoresActuales--;
            }else{
                JOptionPane.showMessageDialog(null, "No puedes eliminar mas productores");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Primero presiona empezar porfavor");
        }
    }//GEN-LAST:event_btnEliminarProductorActionPerformed

    private void btnEliminarConsumidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarConsumidorActionPerformed
        // TODO add your handling code here:
        if(listaProductores[0].isAlive()){
            if(consumidoresActuales>0){
                listaConsumidores[consumidoresActuales].terminarHilo();
                consumidoresActuales--;
            }else{
                JOptionPane.showMessageDialog(null, "No puedes eliminar mas consumidores");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Primero presiona empezar porfavor");
        }
    }//GEN-LAST:event_btnEliminarConsumidorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Interfaz().setVisible(true);
            }

            
        });
        
    }
    
    public void actualizarVentana(){
        Thread ventana = new Thread(()->{
            while(!Thread.currentThread().isInterrupted()){
                lblCantidadProductores.setText("Productores: "+(productoresActuales+1));
                lblCantidadConsumidores.setText("Consumidores: "+(consumidoresActuales+1));
                if (cantidadActual!= bufferPrincipal.getCantidadProductos()){
                    cantidadActual= bufferPrincipal.getCantidadProductos();
                    pintar();
                }
                lblCantidadActual.setText("Cantidad actual: " + cantidadActual);
                
                
                if(listaProductores[0].isDespierto()){
                    icono = new ImageIcon(getClass().getResource("/imagenes/productor producir.gif"));
                    imgProductor.setIcon(icono);
                }else{
                    icono = new ImageIcon(getClass().getResource("/imagenes/productor dormir.gif"));
                    imgProductor.setIcon(icono);
                }

                if(listaConsumidores[0].isDespierto()){
                    icono = new ImageIcon(getClass().getResource("/imagenes/consumidor consumir.gif"));
                    imgConsumidor.setIcon(icono);
                }else{
                    icono = new ImageIcon(getClass().getResource("/imagenes/consumidor dormir.gif"));
                    imgConsumidor.setIcon(icono);
                }
            }
        });
        ventana.start();
        
            
        
    }
    
    public void pintar(){
        
        for(int i = 0;i<10;i++){
            productos[i].setVisible(false);
        }
        
        for(int i = 0;i<cantidadActual;i++){
            productos[i].setVisible(true);
        }
        
        panelPrincipal.updateUI();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarConsumidor;
    private javax.swing.JButton btnAgregarProductor;
    private javax.swing.JButton btnEliminarConsumidor;
    private javax.swing.JButton btnEliminarProductor;
    private javax.swing.JButton btnEmpezar;
    private javax.swing.JButton btnRestarAlmacen;
    private javax.swing.JButton btnSumarAlmacen;
    private javax.swing.JLabel imgConsumidor;
    private javax.swing.JLabel imgProductor;
    private javax.swing.JLabel lblAlmacen;
    private javax.swing.JLabel lblCantidadActual;
    private javax.swing.JLabel lblCantidadConsumidores;
    private javax.swing.JLabel lblCantidadProductores;
    private javax.swing.JLabel lblConsumidor;
    private javax.swing.JLabel lblProductor;
    private javax.swing.JLabel lblPrograma;
    private javax.swing.JLabel lblStatusPrograma;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
